// Code generated by protoc-gen-go. DO NOT EDIT.
// source: city.proto

package geo_proto_city

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Событие запроса на city
type CityEventRequest struct {
	// Имя обменника куда слать событие ответа
	ResponseTopic string `protobuf:"bytes,1,opt,name=responseTopic,proto3" json:"responseTopic,omitempty"`
	// Название
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityEventRequest) Reset()         { *m = CityEventRequest{} }
func (m *CityEventRequest) String() string { return proto.CompactTextString(m) }
func (*CityEventRequest) ProtoMessage()    {}
func (*CityEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_city_465b3b310b93ef2a, []int{0}
}
func (m *CityEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityEventRequest.Unmarshal(m, b)
}
func (m *CityEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityEventRequest.Marshal(b, m, deterministic)
}
func (dst *CityEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityEventRequest.Merge(dst, src)
}
func (m *CityEventRequest) XXX_Size() int {
	return xxx_messageInfo_CityEventRequest.Size(m)
}
func (m *CityEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CityEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CityEventRequest proto.InternalMessageInfo

func (m *CityEventRequest) GetResponseTopic() string {
	if m != nil {
		return m.ResponseTopic
	}
	return ""
}

func (m *CityEventRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Событие ответа на city
type CityEventResponse struct {
	// Название
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Список станций
	Stations []string `protobuf:"bytes,2,rep,name=stations,proto3" json:"stations,omitempty"`
	// Описание ошибки
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Временная метка операции
	Ts                   string   `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityEventResponse) Reset()         { *m = CityEventResponse{} }
func (m *CityEventResponse) String() string { return proto.CompactTextString(m) }
func (*CityEventResponse) ProtoMessage()    {}
func (*CityEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_city_465b3b310b93ef2a, []int{1}
}
func (m *CityEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityEventResponse.Unmarshal(m, b)
}
func (m *CityEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityEventResponse.Marshal(b, m, deterministic)
}
func (dst *CityEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityEventResponse.Merge(dst, src)
}
func (m *CityEventResponse) XXX_Size() int {
	return xxx_messageInfo_CityEventResponse.Size(m)
}
func (m *CityEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CityEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CityEventResponse proto.InternalMessageInfo

func (m *CityEventResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CityEventResponse) GetStations() []string {
	if m != nil {
		return m.Stations
	}
	return nil
}

func (m *CityEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CityEventResponse) GetTs() string {
	if m != nil {
		return m.Ts
	}
	return ""
}

func init() {
	proto.RegisterType((*CityEventRequest)(nil), "geo.proto.city.CityEventRequest")
	proto.RegisterType((*CityEventResponse)(nil), "geo.proto.city.CityEventResponse")
}

func init() { proto.RegisterFile("city.proto", fileDescriptor_city_465b3b310b93ef2a) }

var fileDescriptor_city_465b3b310b93ef2a = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x31, 0xcb, 0xc2, 0x40,
	0x0c, 0x86, 0xe9, 0xb5, 0xdf, 0x87, 0x0d, 0x58, 0x34, 0x38, 0x1c, 0x4e, 0xa5, 0x38, 0x74, 0xea,
	0xe2, 0x4f, 0x10, 0x37, 0xa7, 0xe2, 0x1f, 0xa8, 0x25, 0xc8, 0x0d, 0x5e, 0xea, 0x25, 0x0a, 0xfd,
	0xf7, 0xe2, 0x15, 0xaa, 0x6e, 0xef, 0xfb, 0xe4, 0x49, 0x20, 0x00, 0xbd, 0xd3, 0xb1, 0x19, 0x02,
	0x2b, 0x63, 0x71, 0x25, 0x9e, 0x62, 0xf3, 0xa6, 0xd5, 0x09, 0x56, 0x07, 0xa7, 0xe3, 0xf1, 0x49,
	0x5e, 0x5b, 0xba, 0x3f, 0x48, 0x14, 0x77, 0xb0, 0x0c, 0x24, 0x03, 0x7b, 0xa1, 0x33, 0x0f, 0xae,
	0xb7, 0x49, 0x99, 0xd4, 0x79, 0xfb, 0x0b, 0x11, 0x21, 0xf3, 0xdd, 0x8d, 0xac, 0x89, 0xc3, 0x98,
	0x2b, 0x07, 0xeb, 0xaf, 0x6b, 0x93, 0x3d, 0x8b, 0xc9, 0x47, 0xc4, 0x2d, 0x2c, 0x44, 0x3b, 0x75,
	0xec, 0xc5, 0x9a, 0x32, 0xad, 0xf3, 0x76, 0xee, 0xb8, 0x81, 0x3f, 0x0a, 0x81, 0x83, 0x4d, 0xe3,
	0xc2, 0x54, 0xb0, 0x00, 0xa3, 0x62, 0xb3, 0x88, 0x8c, 0xca, 0xe5, 0x3f, 0x3e, 0xb1, 0x7f, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xb3, 0x73, 0x01, 0x67, 0xdd, 0x00, 0x00, 0x00,
}
