// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package geo_proto_task_worker_search

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Событие ответа на task.worker.search
type TaskWorkerSearchRunEventResponse struct {
	// Название
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Описание ошибки
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Временная метка операции
	Ts                   string   `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskWorkerSearchRunEventResponse) Reset()         { *m = TaskWorkerSearchRunEventResponse{} }
func (m *TaskWorkerSearchRunEventResponse) String() string { return proto.CompactTextString(m) }
func (*TaskWorkerSearchRunEventResponse) ProtoMessage()    {}
func (*TaskWorkerSearchRunEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_513ec9c68e3fee48, []int{0}
}
func (m *TaskWorkerSearchRunEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskWorkerSearchRunEventResponse.Unmarshal(m, b)
}
func (m *TaskWorkerSearchRunEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskWorkerSearchRunEventResponse.Marshal(b, m, deterministic)
}
func (dst *TaskWorkerSearchRunEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskWorkerSearchRunEventResponse.Merge(dst, src)
}
func (m *TaskWorkerSearchRunEventResponse) XXX_Size() int {
	return xxx_messageInfo_TaskWorkerSearchRunEventResponse.Size(m)
}
func (m *TaskWorkerSearchRunEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskWorkerSearchRunEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskWorkerSearchRunEventResponse proto.InternalMessageInfo

func (m *TaskWorkerSearchRunEventResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskWorkerSearchRunEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *TaskWorkerSearchRunEventResponse) GetTs() string {
	if m != nil {
		return m.Ts
	}
	return ""
}

// Событие лога на task.worker.search
type TaskWorkerSearchRunEventLog struct {
	// Название
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Список описаний ошибок
	Messages []*TaskWorkerSearchRunEventLog_Messages `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	// Временная метка операции
	Ts                   string   `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskWorkerSearchRunEventLog) Reset()         { *m = TaskWorkerSearchRunEventLog{} }
func (m *TaskWorkerSearchRunEventLog) String() string { return proto.CompactTextString(m) }
func (*TaskWorkerSearchRunEventLog) ProtoMessage()    {}
func (*TaskWorkerSearchRunEventLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_513ec9c68e3fee48, []int{1}
}
func (m *TaskWorkerSearchRunEventLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskWorkerSearchRunEventLog.Unmarshal(m, b)
}
func (m *TaskWorkerSearchRunEventLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskWorkerSearchRunEventLog.Marshal(b, m, deterministic)
}
func (dst *TaskWorkerSearchRunEventLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskWorkerSearchRunEventLog.Merge(dst, src)
}
func (m *TaskWorkerSearchRunEventLog) XXX_Size() int {
	return xxx_messageInfo_TaskWorkerSearchRunEventLog.Size(m)
}
func (m *TaskWorkerSearchRunEventLog) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskWorkerSearchRunEventLog.DiscardUnknown(m)
}

var xxx_messageInfo_TaskWorkerSearchRunEventLog proto.InternalMessageInfo

func (m *TaskWorkerSearchRunEventLog) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskWorkerSearchRunEventLog) GetMessages() []*TaskWorkerSearchRunEventLog_Messages {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *TaskWorkerSearchRunEventLog) GetTs() string {
	if m != nil {
		return m.Ts
	}
	return ""
}

// Структура описания ошибки
type TaskWorkerSearchRunEventLog_Messages struct {
	// Описание ошибки
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Счетчик ошибок
	Counter uint32 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	// Последняя временная метка ошибки
	Ts                   string   `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskWorkerSearchRunEventLog_Messages) Reset()         { *m = TaskWorkerSearchRunEventLog_Messages{} }
func (m *TaskWorkerSearchRunEventLog_Messages) String() string { return proto.CompactTextString(m) }
func (*TaskWorkerSearchRunEventLog_Messages) ProtoMessage()    {}
func (*TaskWorkerSearchRunEventLog_Messages) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_513ec9c68e3fee48, []int{1, 0}
}
func (m *TaskWorkerSearchRunEventLog_Messages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskWorkerSearchRunEventLog_Messages.Unmarshal(m, b)
}
func (m *TaskWorkerSearchRunEventLog_Messages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskWorkerSearchRunEventLog_Messages.Marshal(b, m, deterministic)
}
func (dst *TaskWorkerSearchRunEventLog_Messages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskWorkerSearchRunEventLog_Messages.Merge(dst, src)
}
func (m *TaskWorkerSearchRunEventLog_Messages) XXX_Size() int {
	return xxx_messageInfo_TaskWorkerSearchRunEventLog_Messages.Size(m)
}
func (m *TaskWorkerSearchRunEventLog_Messages) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskWorkerSearchRunEventLog_Messages.DiscardUnknown(m)
}

var xxx_messageInfo_TaskWorkerSearchRunEventLog_Messages proto.InternalMessageInfo

func (m *TaskWorkerSearchRunEventLog_Messages) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TaskWorkerSearchRunEventLog_Messages) GetCounter() uint32 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func (m *TaskWorkerSearchRunEventLog_Messages) GetTs() string {
	if m != nil {
		return m.Ts
	}
	return ""
}

// Запрос на TaskWorkerSearchRun
type TaskWorkerSearchRunRpcRequest struct {
	// Имя обменника куда слать событие ответа
	ResponseTopic string `protobuf:"bytes,1,opt,name=responseTopic,proto3" json:"responseTopic,omitempty"`
	// Имя обменника куда слать событие лога
	LogTopic string `protobuf:"bytes,2,opt,name=logTopic,proto3" json:"logTopic,omitempty"`
	// Название
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Список UUID воркеров
	ListWorkerUUID       []string `protobuf:"bytes,5,rep,name=listWorkerUUID,proto3" json:"listWorkerUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskWorkerSearchRunRpcRequest) Reset()         { *m = TaskWorkerSearchRunRpcRequest{} }
func (m *TaskWorkerSearchRunRpcRequest) String() string { return proto.CompactTextString(m) }
func (*TaskWorkerSearchRunRpcRequest) ProtoMessage()    {}
func (*TaskWorkerSearchRunRpcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_513ec9c68e3fee48, []int{2}
}
func (m *TaskWorkerSearchRunRpcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskWorkerSearchRunRpcRequest.Unmarshal(m, b)
}
func (m *TaskWorkerSearchRunRpcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskWorkerSearchRunRpcRequest.Marshal(b, m, deterministic)
}
func (dst *TaskWorkerSearchRunRpcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskWorkerSearchRunRpcRequest.Merge(dst, src)
}
func (m *TaskWorkerSearchRunRpcRequest) XXX_Size() int {
	return xxx_messageInfo_TaskWorkerSearchRunRpcRequest.Size(m)
}
func (m *TaskWorkerSearchRunRpcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskWorkerSearchRunRpcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskWorkerSearchRunRpcRequest proto.InternalMessageInfo

func (m *TaskWorkerSearchRunRpcRequest) GetResponseTopic() string {
	if m != nil {
		return m.ResponseTopic
	}
	return ""
}

func (m *TaskWorkerSearchRunRpcRequest) GetLogTopic() string {
	if m != nil {
		return m.LogTopic
	}
	return ""
}

func (m *TaskWorkerSearchRunRpcRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskWorkerSearchRunRpcRequest) GetListWorkerUUID() []string {
	if m != nil {
		return m.ListWorkerUUID
	}
	return nil
}

// Ответ на TaskWorkerSearchRun
type TaskWorkerSearchRunRpcResponse struct {
	// Описание ошибки
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Временная метка операции
	Ts                   string   `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskWorkerSearchRunRpcResponse) Reset()         { *m = TaskWorkerSearchRunRpcResponse{} }
func (m *TaskWorkerSearchRunRpcResponse) String() string { return proto.CompactTextString(m) }
func (*TaskWorkerSearchRunRpcResponse) ProtoMessage()    {}
func (*TaskWorkerSearchRunRpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_513ec9c68e3fee48, []int{3}
}
func (m *TaskWorkerSearchRunRpcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskWorkerSearchRunRpcResponse.Unmarshal(m, b)
}
func (m *TaskWorkerSearchRunRpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskWorkerSearchRunRpcResponse.Marshal(b, m, deterministic)
}
func (dst *TaskWorkerSearchRunRpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskWorkerSearchRunRpcResponse.Merge(dst, src)
}
func (m *TaskWorkerSearchRunRpcResponse) XXX_Size() int {
	return xxx_messageInfo_TaskWorkerSearchRunRpcResponse.Size(m)
}
func (m *TaskWorkerSearchRunRpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskWorkerSearchRunRpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskWorkerSearchRunRpcResponse proto.InternalMessageInfo

func (m *TaskWorkerSearchRunRpcResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *TaskWorkerSearchRunRpcResponse) GetTs() string {
	if m != nil {
		return m.Ts
	}
	return ""
}

// Запрос на TaskWorkerSearchStop
type TaskWorkerSearchStopRpcRequest struct {
	// Название
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskWorkerSearchStopRpcRequest) Reset()         { *m = TaskWorkerSearchStopRpcRequest{} }
func (m *TaskWorkerSearchStopRpcRequest) String() string { return proto.CompactTextString(m) }
func (*TaskWorkerSearchStopRpcRequest) ProtoMessage()    {}
func (*TaskWorkerSearchStopRpcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_513ec9c68e3fee48, []int{4}
}
func (m *TaskWorkerSearchStopRpcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskWorkerSearchStopRpcRequest.Unmarshal(m, b)
}
func (m *TaskWorkerSearchStopRpcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskWorkerSearchStopRpcRequest.Marshal(b, m, deterministic)
}
func (dst *TaskWorkerSearchStopRpcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskWorkerSearchStopRpcRequest.Merge(dst, src)
}
func (m *TaskWorkerSearchStopRpcRequest) XXX_Size() int {
	return xxx_messageInfo_TaskWorkerSearchStopRpcRequest.Size(m)
}
func (m *TaskWorkerSearchStopRpcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskWorkerSearchStopRpcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskWorkerSearchStopRpcRequest proto.InternalMessageInfo

func (m *TaskWorkerSearchStopRpcRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Ответ на TaskWorkerSearchStop
type TaskWorkerSearchStopRpcResponse struct {
	// Описание ошибки
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Временная метка операции
	Ts                   string   `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskWorkerSearchStopRpcResponse) Reset()         { *m = TaskWorkerSearchStopRpcResponse{} }
func (m *TaskWorkerSearchStopRpcResponse) String() string { return proto.CompactTextString(m) }
func (*TaskWorkerSearchStopRpcResponse) ProtoMessage()    {}
func (*TaskWorkerSearchStopRpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_513ec9c68e3fee48, []int{5}
}
func (m *TaskWorkerSearchStopRpcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskWorkerSearchStopRpcResponse.Unmarshal(m, b)
}
func (m *TaskWorkerSearchStopRpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskWorkerSearchStopRpcResponse.Marshal(b, m, deterministic)
}
func (dst *TaskWorkerSearchStopRpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskWorkerSearchStopRpcResponse.Merge(dst, src)
}
func (m *TaskWorkerSearchStopRpcResponse) XXX_Size() int {
	return xxx_messageInfo_TaskWorkerSearchStopRpcResponse.Size(m)
}
func (m *TaskWorkerSearchStopRpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskWorkerSearchStopRpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskWorkerSearchStopRpcResponse proto.InternalMessageInfo

func (m *TaskWorkerSearchStopRpcResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *TaskWorkerSearchStopRpcResponse) GetTs() string {
	if m != nil {
		return m.Ts
	}
	return ""
}

func init() {
	proto.RegisterType((*TaskWorkerSearchRunEventResponse)(nil), "geo.proto.task.worker.search.TaskWorkerSearchRunEventResponse")
	proto.RegisterType((*TaskWorkerSearchRunEventLog)(nil), "geo.proto.task.worker.search.TaskWorkerSearchRunEventLog")
	proto.RegisterType((*TaskWorkerSearchRunEventLog_Messages)(nil), "geo.proto.task.worker.search.TaskWorkerSearchRunEventLog.Messages")
	proto.RegisterType((*TaskWorkerSearchRunRpcRequest)(nil), "geo.proto.task.worker.search.TaskWorkerSearchRunRpcRequest")
	proto.RegisterType((*TaskWorkerSearchRunRpcResponse)(nil), "geo.proto.task.worker.search.TaskWorkerSearchRunRpcResponse")
	proto.RegisterType((*TaskWorkerSearchStopRpcRequest)(nil), "geo.proto.task.worker.search.TaskWorkerSearchStopRpcRequest")
	proto.RegisterType((*TaskWorkerSearchStopRpcResponse)(nil), "geo.proto.task.worker.search.TaskWorkerSearchStopRpcResponse")
}

func init() { proto.RegisterFile("search.proto", fileDescriptor_search_513ec9c68e3fee48) }

var fileDescriptor_search_513ec9c68e3fee48 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x25, 0x49, 0x0b, 0xed, 0x85, 0x76, 0x30, 0x1d, 0xa2, 0xf0, 0x8a, 0x22, 0x84, 0x3a, 0x79,
	0x28, 0x6c, 0xc0, 0x82, 0x78, 0x08, 0x09, 0x18, 0xdc, 0x56, 0x2c, 0x08, 0x29, 0x44, 0x56, 0xa8,
	0xda, 0xc6, 0xc1, 0x76, 0xe1, 0x3f, 0x90, 0x18, 0xf9, 0x01, 0x06, 0xfe, 0x8d, 0x3f, 0x40, 0xd8,
	0x49, 0xe8, 0x23, 0xa9, 0xd4, 0x6e, 0xb9, 0xc7, 0xf7, 0x9e, 0x7b, 0xce, 0xb9, 0x81, 0x0d, 0x41,
	0x7d, 0x1e, 0x3c, 0xe3, 0x98, 0x33, 0xc9, 0xd0, 0x76, 0x48, 0x99, 0xfe, 0xc4, 0xd2, 0x17, 0x7d,
	0xfc, 0xc6, 0x78, 0x9f, 0x72, 0xac, 0x7b, 0xbc, 0x07, 0x70, 0x3b, 0xbe, 0xe8, 0xdf, 0x2b, 0xb0,
	0xad, 0x30, 0x32, 0x8a, 0x2e, 0x5e, 0x69, 0x24, 0x09, 0x15, 0x31, 0x8b, 0x04, 0x45, 0x08, 0x4a,
	0x91, 0x3f, 0xa4, 0xb6, 0xe9, 0x1a, 0xcd, 0x2a, 0x51, 0xdf, 0xa8, 0x01, 0x65, 0xca, 0x39, 0xe3,
	0xb6, 0xa5, 0x40, 0x5d, 0xa0, 0x3a, 0x98, 0x52, 0xd8, 0x25, 0x05, 0x99, 0x52, 0x78, 0x3f, 0x06,
	0x6c, 0x15, 0xd1, 0xdf, 0xb0, 0x30, 0x97, 0xf9, 0x11, 0x2a, 0x43, 0x2a, 0x84, 0x1f, 0x52, 0x61,
	0x5b, 0xae, 0xd5, 0x5c, 0x6f, 0x9d, 0xe1, 0x79, 0x16, 0xf0, 0x9c, 0x05, 0xf8, 0x36, 0x61, 0x22,
	0x19, 0xe7, 0xb4, 0x46, 0xe7, 0x0e, 0x2a, 0x69, 0x17, 0xb2, 0x61, 0x2d, 0xe9, 0xb3, 0x0d, 0xd5,
	0x90, 0x96, 0x7f, 0x2f, 0x01, 0x1b, 0x45, 0x92, 0x72, 0x25, 0xb6, 0x46, 0xd2, 0x32, 0xe1, 0xb3,
	0x32, 0xcf, 0x9f, 0x06, 0xec, 0xe4, 0x48, 0x22, 0x71, 0x40, 0xe8, 0xcb, 0x88, 0x0a, 0x89, 0xf6,
	0xa1, 0xc6, 0x93, 0x6c, 0x3b, 0x2c, 0xee, 0x05, 0xc9, 0xae, 0x49, 0x10, 0x39, 0x50, 0x19, 0xb0,
	0x50, 0x37, 0xe8, 0x7c, 0xb2, 0x3a, 0xcb, 0xad, 0x34, 0x96, 0xdb, 0x01, 0xd4, 0x07, 0x3d, 0x21,
	0xf5, 0xda, 0x6e, 0xf7, 0xfa, 0xdc, 0x2e, 0xbb, 0x56, 0xb3, 0x4a, 0xa6, 0x50, 0xef, 0x12, 0x76,
	0x8b, 0xe4, 0x25, 0xf7, 0xce, 0x6e, 0x6b, 0xcc, 0xde, 0xd6, 0xcc, 0x7c, 0x1e, 0xcd, 0xf2, 0xb4,
	0x25, 0x8b, 0xc7, 0x7c, 0xe6, 0x5c, 0xd7, 0xbb, 0x82, 0xbd, 0xc2, 0xa9, 0x45, 0xd6, 0xb7, 0xbe,
	0x0c, 0xd8, 0xcc, 0xf1, 0x81, 0xde, 0x0b, 0xf0, 0xe3, 0x85, 0x7f, 0xa2, 0x7f, 0x27, 0xce, 0xc9,
	0x72, 0xc3, 0xda, 0x90, 0xb7, 0xd2, 0xfa, 0x36, 0xa0, 0x91, 0x67, 0x1b, 0x7d, 0x14, 0x3d, 0x2c,
	0xb8, 0x71, 0x32, 0x79, 0xe7, 0x74, 0xc9, 0xe9, 0x54, 0xf0, 0xd3, 0xaa, 0x9a, 0x3d, 0xfc, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0xaa, 0x26, 0x06, 0x3b, 0x4b, 0x04, 0x00, 0x00,
}
