// Code generated by protoc-gen-go. DO NOT EDIT.
// source: register.proto

package geo_proto_register

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Событие на register
type RegisterEvent struct {
	// id ворекра в nats-сети
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Временная метка операции
	Ts                   string   `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterEvent) Reset()         { *m = RegisterEvent{} }
func (m *RegisterEvent) String() string { return proto.CompactTextString(m) }
func (*RegisterEvent) ProtoMessage()    {}
func (*RegisterEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_register_6f5b44ade7edff98, []int{0}
}
func (m *RegisterEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterEvent.Unmarshal(m, b)
}
func (m *RegisterEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterEvent.Marshal(b, m, deterministic)
}
func (dst *RegisterEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterEvent.Merge(dst, src)
}
func (m *RegisterEvent) XXX_Size() int {
	return xxx_messageInfo_RegisterEvent.Size(m)
}
func (m *RegisterEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterEvent proto.InternalMessageInfo

func (m *RegisterEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterEvent) GetTs() string {
	if m != nil {
		return m.Ts
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterEvent)(nil), "geo.proto.register.RegisterEvent")
}

func init() { proto.RegisterFile("register.proto", fileDescriptor_register_6f5b44ade7edff98) }

var fileDescriptor_register_6f5b44ade7edff98 = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x4d, 0xcf,
	0x2c, 0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4a, 0x4f, 0xcd, 0x87,
	0x30, 0xf5, 0x60, 0x32, 0x4a, 0xfa, 0x5c, 0xbc, 0x41, 0x50, 0xb6, 0x6b, 0x59, 0x6a, 0x5e, 0x89,
	0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x66, 0x0a,
	0x88, 0x5f, 0x52, 0x2c, 0xc1, 0x04, 0xe1, 0x97, 0x14, 0x27, 0xb1, 0x81, 0x0d, 0x30, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x2e, 0xe3, 0x5e, 0xd1, 0x5d, 0x00, 0x00, 0x00,
}
